{
 "title": "Nuxeo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nuxeo nodes",
   "type": "singlestat",
   "description": "The number of Nuxeo nodes in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.nuxeo.instance-up.count)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "description": "The number of errors in the Nuxeo's log for the running instances.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.{error,fatal}.count)"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "singlestat",
   "description": "The number of warnings in the Nuxeo's log for the running instances.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.warn.count)"
    }
   ]
  },
  {
   "title": "All",
   "type": "singlestat",
   "description": "The Nuxeo's log activity for the running instances.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.all.count)"
    }
   ]
  },
  {
   "title": "Errors and warnings",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.error.count, 9)"
    },
    {
     "target": "aliasByNode(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.fatal.count, 9)"
    },
    {
     "target": "aliasByNode(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.warn.count, 9)"
    }
   ]
  },
  {
   "title": "Stream Failure",
   "type": "singlestat",
   "description": "The number of Stream processing computation terminated due to failure after applying the retry policy. A manual restart of Nuxeo is required to continue the processing, this must be done within the stream retention policy (7 days by default when using Kafka).",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.nuxeo.stream.failure.count)"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.jvm.threads.*.count, 1), 4)"
      }
     ]
    },
    {
     "title": "Threads per JVM",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.threads.count, 1)"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.memory.heap.usage, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.memory.*.used, 1, 5)"
      }
     ]
    },
    {
     "title": "Garbage Collector",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.garbage.PS-MarkSweep.time, 1, 5)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.garbage.PS-Scavenge.time, 1, 5)"
      }
     ]
    },
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.buffers.*.used, 1, 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stream processor in failure",
     "type": "graph",
     "description": "Nuxeo node with failure needs to be restarted.",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(currentAbove(servers.*.nuxeo.nuxeo.stream.computation.*.failure.count, 0), 2, 6)"
      }
     ]
    },
    {
     "title": "Records skipped due to failure",
     "type": "graph",
     "description": "This count the number of records skipped because the computation policy is configured to continue on failure. This requires some attention to understand why these records have been skipped.",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "records" }
     ],
     "targets": [
      {
       "target": "aliasByNode(currentAbove(servers.*.nuxeo.nuxeo.stream.computation.*.skippedRecord.count, 0), 2, 6)"
      }
     ]
    },
    {
     "title": "Streams Lag and Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.streams.*.*.all.lag, 5, 7)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.streams.*.*.all.latency, 5, 7)"
      }
     ]
    },
    {
     "title": "Streams Positions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.streams.*.*.all.{pos,end}, 5, 7)"
      }
     ]
    },
    {
     "title": "Most deviant Partition Lag",
     "type": "graph",
     "description": "The 5 most deviant lag per partition.",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(mostDeviant(servers.*.nuxeo.streams.*.*.p*.lag, 5), 5, 6)"
      }
     ]
    },
    {
     "title": "Top throughput records/min",
     "type": "graph",
     "description": "The 5 computations that process the most record per minute.",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 44 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestAverage(servers.*.nuxeo.nuxeo.stream.computation.*.processRecord.m1_rate, 5), 2, 6)"
      }
     ]
    },
    {
     "title": "Slowest record processing",
     "type": "graph",
     "description": "The 5 slowest computations when processing record (mean).",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestAverage(servers.*.nuxeo.nuxeo.stream.computation.*.processRecord.mean, 5), 2, 6)"
      }
     ]
    },
    {
     "title": "Slowest timer processing",
     "type": "graph",
     "description": "The 5 slowest computations when processing their timer (mean).",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 52 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestAverage(servers.*.nuxeo.nuxeo.stream.computation.*.processTimer.mean, 5), 2, 6)"
      }
     ]
    }
   ]
  }
 ]
}