server:
  port: 8080
  host: 0.0.0.0

org:
  nuxeo:
    runtime:
      redirectJUL: true

redis:
  port: 6379
  host: localhost
  prefix: "test:msp:"

computation:
  acme:
    concurrency: 4
  counter:
    concurrency: 1
    batch:
      capacity: 10
      threshold: "500ms"
