FROM openjdk:11-jre-slim

WORKDIR /work/
COPY target/*.jar /work/application.jar
COPY target/libs /work/libs
EXPOSE 8080

# Run the CMD in bash to avoid running the process with the PID 1 and ending up with this error https://github.com/docker-library/openjdk/issues/76
CMD java -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n -jar /work/application.jar
